language: node_js
node_js: 12

install: npm install

script:
  - npm test
  - npm run build

before_deploy: cp -R public/ docs

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  edge: true
  skip_cleanup: true
