/**
  * Automatically generated with `node ./generate-page.js`
  * Please do not edit this file directly
  * Last updated: 2019-12-22T11:21:35.813Z
  */

import React from 'react';

import VisualizationPage from 'components/visualization-page';
import BubbleSort from 'algorithms/algorithms/bubble-sort';
import data from 'data/algorithms/bubble-sort.json';

const BubbleSortPage = () => {
    return (
        <VisualizationPage
            algorithm={new BubbleSort()}
            inputs={data.data}
        />
    );
};

export default BubbleSortPage;
        